In [1]:
#!/usr/bin/env python3
import sys 
sys.path.insert(0, '/uufs/chpc.utah.edu/common/home/koper-group4/bbaker/waveformArchive/gcc_build')
#sys.path.insert(0, '/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/templateMatchingSource/rtseis/notchpeak4_gcc83_build/')
sys.path.insert(0, '/uufs/chpc.utah.edu/common/home/koper-group4/bbaker/mlmodels/intel_cpu_build')
sys.path.insert(0, '/uufs/chpc.utah.edu/common/home/koper-group4/bbaker/mlmodels/features/np4_build')
import h5py
import pyWaveformArchive as pwa 
import pyuussmlmodels as uuss
import pyuussFeatures as pf
# import libpyrtseis as rtseis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timezone

import glob

# S-arrivals

In [2]:
archive_dir = '/uufs/chpc.utah.edu/common/home/koper-group4/bbaker/waveformArchive/archives/'
h5_archive_files = glob.glob(archive_dir + '/archive_????.h5')
catalog_dir = '/uufs/chpc.utah.edu/common/home/koper-group3/alysha/ben_catalogs/20240220'
arrival_catalog_3c = f'{catalog_dir}/currentEarthquakeArrivalInformation3CWithGains.csv'
startdate = datetime(2002, 1, 1, tzinfo=timezone.utc).timestamp()
print(f'Using events occuring on or after {startdate}')

print("Loading arrival catalog...")
arrival_catalog_df = pd.read_csv(arrival_catalog_3c, dtype = {'location' : object})
# Regress on Ml for S waves
arrival_catalog_df = arrival_catalog_df[ (arrival_catalog_df.phase == 'S') &
                                            (arrival_catalog_df.magnitude_type == 'l') &
                                            (arrival_catalog_df.origin_time >= startdate) ]
# # Focus on Yellowstone
arrival_catalog_df = arrival_catalog_df[ (arrival_catalog_df.event_lat > 44) &
                                            (arrival_catalog_df.event_lat < 45.167) &
                                            (arrival_catalog_df.event_lon > -111.333) &
                                            (arrival_catalog_df.event_lon < -109.75) ]

print("Opening archive files for reading...")
archive_manager = pwa.ArchiveManager()
archive_manager.open_files_for_reading(h5_archive_files)

Using events occuring on or after 1009843200.0
Loading arrival catalog...
Opening archive files for reading...

In [3]:
arrival_catalog_df["location"].value_counts()

location
01    18686
       5066
00      584
Name: count, dtype: int64

In [4]:
arrival_catalog_df.head()

,evid,network,station,location,channelz,channel1,channel2,phase,arrival_id,arrival_time,...,low_freq_corners_2,high_freq_corners_z,high_freq_corners_1,high_freq_corners_2,channel_dip_z,channel_azimuth_z,channel_dip_1,channel_azimuth_1,channel_dip_2,channel_azimuth_2
344,60000620,TA,H17A,01,BHZ,BHN,BHE,S,10013548,1.357546e+09,...,16.0,0.008330,0.008330,0.008330,-90.0,0.0,0.0,0.1,0.0,90.1
345,60000620,PB,B208,01,EHZ,EHN,EHE,S,10013551,1.357546e+09,...,40.0,0.003993,0.003993,0.003993,-90.0,0.0,0.0,30.0,0.0,120.0
349,60000622,WY,YHB,01,HHZ,HHN,HHE,S,10000492,1.349570e+09,...,40.0,4.204171,4.204171,3.564715,-90.0,0.0,0.0,0.0,0.0,90.0
352,60000622,WY,YHL,01,HHZ,HHN,HHE,S,10000494,1.349570e+09,...,40.0,4.204196,4.204196,4.204196,-90.0,0.0,0.0,0.0,0.0,90.0
353,60000622,WY,YMR,01,HHZ,HHN,HHE,S,10000497,1.349570e+09,...,40.0,4.204196,4.204196,4.204196,-90.0,0.0,0.0,0.0,0.0,90.0

In [5]:
arrival_catalog_df.columns

Index(['evid', 'network', 'station', 'location', 'channelz', 'channel1',
       'channel2', 'phase', 'arrival_id', 'arrival_time', 'pick_quality',
       'first_motion', 'take_off_angle', 'source_receiver_distance',
       'source_receiver_azimuth', 'travel_time_residual', 'receiver_lat',
       'receiver_lon', 'receiver_elev', 'event_lat', 'event_lon',
       'event_depth', 'origin_time', 'magnitude', 'magnitude_type', 'rflag',
       'gain_z', 'gain_1', 'gain_2', 'gain_units', 'low_freq_corners_z',
       'low_freq_corners_1', 'low_freq_corners_2', 'high_freq_corners_z',
       'high_freq_corners_1', 'high_freq_corners_2', 'channel_dip_z',
       'channel_azimuth_z', 'channel_dip_1', 'channel_azimuth_1',
       'channel_dip_2', 'channel_azimuth_2'],
      dtype='object')

# Split up the channe info

In [6]:
def add_approx_ondates(df, chan_or):
    gains_mindates = []
    gains_maxdates = []
    for i, row in df.iterrows():
        row = row[["network", "station", f"channel{chan_or}", "location", f"gain_{chan_or}", "gain_units"]]
        t_df = arrival_catalog_df[np.all(arrival_catalog_df[["network", "station", f"channel{chan_or}", "location", f"gain_{chan_or}", "gain_units"]] == row, axis=1)]
        mindate = datetime.fromtimestamp(t_df["arrival_time"].min(), tz=timezone.utc)
        maxdate = datetime.fromtimestamp(t_df["arrival_time"].max(), tz=timezone.utc)
        gains_mindates.append(mindate)
        gains_maxdates.append(maxdate)

    df["mindate"] = gains_mindates
    df["maxdate"] = gains_maxdates
    # df.head()

    return df

In [7]:
gainz_df = arrival_catalog_df[['network', 'station', 'location', 'channelz', 'gain_z', 'gain_units', 'channel_dip_z', 'channel_azimuth_z']].drop_duplicates()
gain1_df = arrival_catalog_df[['network', 'station', 'location', 'channel1', 'gain_1', 'gain_units', 'channel_dip_1', 'channel_azimuth_1']].drop_duplicates()
gain2_df = arrival_catalog_df[['network', 'station', 'location', 'channel2', 'gain_2', 'gain_units', 'channel_dip_2', 'channel_azimuth_2']].drop_duplicates()

gainz_df = add_approx_ondates(gainz_df, "z")
gain1_df = add_approx_ondates(gain1_df, "1")
gain2_df = add_approx_ondates(gain2_df, "2")

new_cols = ['network', 'station', 'location', 'channel', 'gain', 'gain_units', 'channel_dip', 'channel_azimuth', "mindate", "maxdate"]
gainz_df.columns = new_cols
gain1_df.columns = new_cols
gain2_df.columns = new_cols
gains_df = pd.concat([gainz_df, gain1_df, gain2_df]).sort_values(["network", "station", "location", "channel", "mindate"])
gains_df.head()

,network,station,location,channel,gain,gain_units,channel_dip,channel_azimuth,mindate,maxdate
12322,IW,FLWY,00,BH1,462429000.0,DU/M/S,0.0,0.0,2016-11-17 06:08:44.755000+00:00,2021-07-31 08:11:14.434572+00:00
47608,IW,FLWY,00,BH1,301720000.0,DU/M/S,0.0,2.8,2021-09-08 17:01:40.424286+00:00,2023-12-17 03:22:16.120020+00:00
12322,IW,FLWY,00,BH2,462429000.0,DU/M/S,0.0,90.0,2016-11-17 06:08:44.755000+00:00,2021-07-31 08:11:14.434572+00:00
47608,IW,FLWY,00,BH2,301720000.0,DU/M/S,0.0,92.8,2021-09-08 17:01:40.424286+00:00,2023-12-17 03:22:16.120020+00:00
12322,IW,FLWY,00,BHZ,462429000.0,DU/M/S,-90.0,0.0,2016-11-17 06:08:44.755000+00:00,2021-07-31 08:11:14.434572+00:00

In [8]:
gains_df[gains_df["station"] == "YMP"]

,network,station,location,channel,gain,gain_units,channel_dip,channel_azimuth,mindate,maxdate
18189,WY,YMP,01,HHE,5.352855e+08,DU/M/S,0.0,90.0,2015-12-07 11:06:32.258523+00:00,2023-03-29 14:10:41.556275+00:00
18189,WY,YMP,01,HHN,5.352855e+08,DU/M/S,0.0,0.0,2015-12-07 11:06:32.258523+00:00,2023-03-29 14:10:41.556275+00:00
18189,WY,YMP,01,HHZ,5.352855e+08,DU/M/S,-90.0,0.0,2015-12-07 11:06:32.258523+00:00,2023-03-29 14:10:41.556275+00:00

# Load in the database channel info

In [9]:
db_gains_df = pd.read_csv("/uufs/chpc.utah.edu/common/home/u1072028/PycharmProjects/seis-proc-db/data_files/db_channel_info.csv",  dtype = {'location' : object}).sort_values(["network", "station", "seed_code", "location"])
db_gains_df["location"] = db_gains_df["location"].fillna("  ")
db_gains_df.head()

,channel_id,network,station,location,seed_code,channel_samp_rate,sensit_units,sensit_freq,sensit_val,gain_vel,receiver_lat,receiver_lon,channel_azimuth,channel_ondate,channel_offdate
3,958,IW,FLWY,00,BH1,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,0.0,2013-07-25 14:46:00,2016-10-22 04:00:00
4,568,IW,FLWY,00,BH1,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2016-10-22 04:00:00,2020-01-30 20:00:00
5,377,IW,FLWY,00,BH1,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,0.0,2020-01-30 20:00:00,2021-08-29 18:00:00
6,4,IW,FLWY,00,BH1,40.0,m/s,0.02,2.939200e+08,2.939199e+08,44.083002,-110.699888,2.8,2021-08-29 18:00:00,NaN
7,959,IW,FLWY,00,BH2,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,90.0,2013-07-25 14:46:00,2016-10-22 04:00:00

In [10]:
# db_gains_df["simple_gain_vel"] = db_gains_df.apply(lambda x: x["sensit_val"]*(2*np.pi*x["sensit_freq"])**-1 if x["sensit_units"] in ["m", "M"] else x["sensit_val"], axis=1)
simple_gain_vels = []
for _, row in db_gains_df.iterrows():
    sensit_val = row["sensit_val"]
    if row["sensit_units"] in ["m", "M"]:
        sensit_val = row["sensit_val"]*(2*np.pi*row["sensit_freq"])**-1
    elif row["sensit_units"] in ["m/s**2", "M/S**2"]:
        sensit_val = row["sensit_val"]*(2*np.pi*row["sensit_freq"])

    simple_gain_vels.append(sensit_val)
db_gains_df["simple_gain_vel"] = simple_gain_vels

# Save matching gain info

In [11]:
matching_gains = []
matching_gains_units = []
for i, row in db_gains_df.iterrows():
    chan_ondate = datetime.strptime(row["channel_ondate"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
    chan_offdate = row["channel_offdate"]
    if type(chan_offdate) == str:    
        chan_offdate = datetime.strptime(chan_offdate, "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
    else:
        chan_offdate = None
    #print(chan_ondate, chan_offdate)
    matching_bb_df = gains_df[(gains_df["network"] == row["network"]) & 
                              (gains_df["station"] == row["station"]) & 
                              (gains_df["channel"] == row["seed_code"]) &
                              (chan_offdate is None or gains_df["mindate"] <= chan_offdate) &
                              (gains_df["maxdate"] >= chan_ondate)]
                                 # & (db_gains_df["sensit_units"].isin(["m", "M"]))]
                                 # & (db_gains_df["location"] == row["location"])]
    matching_gain = None
    matching_gain_units = None
    if len(matching_bb_df) > 0:
        uniq_vals = matching_bb_df["gain"].drop_duplicates().values
        print(row["network"], row["station"], row["seed_code"], row["location"], row["gain_vel"], chan_ondate, chan_offdate, len(matching_bb_df), uniq_vals)
        if len(uniq_vals) > 1:
            date_diffs = matching_bb_df["maxdate"] - chan_ondate
            matching_bb_df = matching_bb_df.iloc[np.argmax(date_diffs):np.argmax(date_diffs)+1]
            print("*", row["network"], row["station"], row["seed_code"], row["location"], row["gain_vel"], chan_ondate, chan_offdate, matching_bb_df["gain"].values)
        
        matching_gain = matching_bb_df["gain"].values[0]
        matching_gain_units = matching_bb_df["gain_units"].values[0]
        #print(matching_bb_df)

    matching_gains.append(matching_gain)
    matching_gains_units.append(matching_gain_units)

IW FLWY BH1 00 462428324.8058124 2016-10-22 04:00:00+00:00 2020-01-30 20:00:00+00:00 1 [4.62429e+08]
IW FLWY BH1 00 462428324.8058124 2020-01-30 20:00:00+00:00 2021-08-29 18:00:00+00:00 1 [4.62429e+08]
IW FLWY BH1 00 293919851.46844804 2021-08-29 18:00:00+00:00 None 1 [3.0172e+08]
IW FLWY BH2 00 462428324.8058124 2016-10-22 04:00:00+00:00 2020-01-30 20:00:00+00:00 1 [4.62429e+08]
IW FLWY BH2 00 462428324.8058124 2020-01-30 20:00:00+00:00 2021-08-29 18:00:00+00:00 1 [4.62429e+08]
IW FLWY BH2 00 293919851.46844804 2021-08-29 18:00:00+00:00 None 1 [3.0172e+08]
IW FLWY BHE    1145993158.470899 2007-03-16 16:46:00+00:00 2013-07-25 14:46:00+00:00 1 [1.25865e+09]
IW FLWY BHN    1145993158.470899 2007-03-16 16:46:00+00:00 2013-07-25 14:46:00+00:00 1 [1.25865e+09]
IW FLWY BHZ 00 1145993158.470899 2013-07-25 14:46:00+00:00 2016-10-22 04:00:00+00:00 1 [1.25865e+09]
IW FLWY BHZ 00 462428324.8058124 2016-10-22 04:00:00+00:00 2020-01-30 20:00:00+00:00 1 [4.62429e+08]
IW FLWY BHZ 00 462428324.8058124 2020-01-30 20:00:00+00:00 2021-08-29 18:00:00+00:00 1 [4.62429e+08]
IW FLWY BHZ 00 293919851.46844804 2021-08-29 18:00:00+00:00 None 1 [3.0172e+08]
IW FLWY BHZ    1145993158.470899 2007-03-16 16:46:00+00:00 2013-07-25 14:46:00+00:00 1 [1.25865e+09]
IW IMW BH1 00 1145993158.470899 2013-07-25 15:11:00+00:00 2023-09-15 17:00:00+00:00 1 [1.25865e+09]
IW IMW BH2 00 1145993158.470899 2013-07-25 15:11:00+00:00 2023-09-15 17:00:00+00:00 1 [1.25865e+09]
IW IMW BHE    1145993158.470899 2006-08-03 20:00:00+00:00 2013-07-25 15:11:00+00:00 1 [1.25865e+09]
IW IMW BHN    1145993158.470899 2006-08-03 20:00:00+00:00 2013-07-25 15:11:00+00:00 1 [1.25865e+09]
IW IMW BHZ 00 1145993158.470899 2013-07-25 15:11:00+00:00 2023-09-15 17:00:00+00:00 2 [1.25865e+09]
IW IMW BHZ    1145993158.470899 2006-08-03 20:00:00+00:00 2013-07-25 15:11:00+00:00 1 [1.25865e+09]
PB B206 EH1    791617774.2662275 2008-06-28 00:00:00+00:00 None 1 [7.81398e+08]
PB B206 EH2    791617774.2662275 2008-06-28 00:00:00+00:00 None 1 [7.81398e+08]
PB B206 EHZ    791617774.2662275 2008-06-28 00:00:00+00:00 None 2 [7.81398e+08]
PB B207 EH1    791617774.2662275 2007-10-20 00:00:00+00:00 None 1 [7.81398e+08]
PB B207 EH2    791617774.2662275 2007-10-20 00:00:00+00:00 None 1 [7.81398e+08]
PB B207 EHZ    791617774.2662275 2007-10-20 00:00:00+00:00 None 2 [7.81398e+08]
PB B208 EH1    791617774.2662275 2007-11-01 00:00:00+00:00 None 1 [7.81398e+08]
PB B208 EH2    791617774.2662275 2007-11-01 00:00:00+00:00 None 1 [7.81398e+08]
PB B208 EHZ    791617774.2662275 2007-11-01 00:00:00+00:00 None 2 [7.81398e+08]
PB B944 EH1    791617774.2662275 2008-08-07 00:00:00+00:00 None 1 [7.81398e+08]
PB B944 EH2    791617774.2662275 2008-08-07 00:00:00+00:00 None 1 [7.81398e+08]
PB B944 EHZ    791617774.2662275 2008-08-07 00:00:00+00:00 None 2 [7.81398e+08]
PB B945 EH1    791617774.2662275 2008-09-04 00:00:00+00:00 None 1 [7.81398e+08]
PB B945 EH2    791617774.2662275 2008-09-04 00:00:00+00:00 None 1 [7.81398e+08]
PB B945 EHZ    791617774.2662275 2008-09-04 00:00:00+00:00 None 2 [7.81398e+08]
PB B950 EH1    791617774.2662275 2013-10-02 00:00:00+00:00 None 1 [7.81398e+08]
PB B950 EH2    791617774.2662275 2013-10-02 00:00:00+00:00 None 1 [7.81398e+08]
PB B950 EHZ    791617774.2662275 2013-10-02 00:00:00+00:00 None 2 [7.81398e+08]
TA H17A BHE    627412927.1611191 2011-08-22 17:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27192e+08]
TA H17A BHN    627412927.1611191 2011-08-22 17:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27192e+08]
TA H17A BHZ    627412927.1611191 2011-08-22 17:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27192e+08]
TA H17A HHE    627732184.8862495 2015-10-16 18:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27604e+08]
TA H17A HHE    627732184.8862495 2016-10-13 18:00:00+00:00 2018-09-04 18:00:00+00:00 1 [6.27604e+08]
TA H17A HHN    627732184.8862495 2015-10-16 18:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27604e+08]
TA H17A HHN    627732184.8862495 2016-10-13 18:00:00+00:00 2018-09-04 18:00:00+00:00 1 [6.27604e+08]
TA H17A HHZ    627732184.8862495 2015-10-16 18:00:00+00:00 2016-10-13 18:00:00+00:00 1 [6.27604e+08]
TA H17A HHZ    627732184.8862495 2016-10-13 18:00:00+00:00 2018-09-04 18:00:00+00:00 1 [6.27604e+08]
US LKWY BH1 00 615726081.5390095 2015-08-23 17:00:00+00:00 2018-09-27 18:00:00+00:00 1 [6.19918e+08]
US LKWY BH1 00 615726081.5390095 2018-09-27 18:00:00+00:00 2019-10-26 19:02:00+00:00 1 [6.19918e+08]
US LKWY BH1 00 615726081.5390095 2019-10-26 19:02:00+00:00 2021-08-12 00:00:00+00:00 1 [6.19918e+08]
US LKWY BH1 00 615726081.5390095 2021-08-12 00:00:00+00:00 2024-07-16 19:00:00+00:00 1 [6.19918e+08]
US LKWY BH2 00 615726081.5390095 2015-08-23 17:00:00+00:00 2018-09-27 18:00:00+00:00 1 [6.19918e+08]
US LKWY BH2 00 615726081.5390095 2018-09-27 18:00:00+00:00 2019-10-26 19:02:00+00:00 1 [6.19918e+08]
US LKWY BH2 00 615726081.5390095 2019-10-26 19:02:00+00:00 2021-08-12 00:00:00+00:00 1 [6.19918e+08]
US LKWY BH2 00 615726081.5390095 2021-08-12 00:00:00+00:00 2024-07-16 19:00:00+00:00 1 [6.19918e+08]
US LKWY BHZ 00 615726081.5390095 2011-08-09 18:00:00+00:00 2015-08-23 17:00:00+00:00 1 [6.19918e+08]
US LKWY BHZ 00 615726081.5390095 2015-08-23 17:00:00+00:00 2018-09-27 18:00:00+00:00 2 [6.19918e+08]
US LKWY BHZ 00 615726081.5390095 2018-09-27 18:00:00+00:00 2019-10-26 19:02:00+00:00 1 [6.19918e+08]
US LKWY BHZ 00 615726081.5390095 2019-10-26 19:02:00+00:00 2021-08-12 00:00:00+00:00 1 [6.19918e+08]
US LKWY BHZ 00 615726081.5390095 2021-08-12 00:00:00+00:00 2024-07-16 19:00:00+00:00 1 [6.19918e+08]
WY YDD HHE 01 648583841.7332102 2018-09-05 00:00:00+00:00 None 1 [6.48583858e+08]
WY YDD HHN 01 648583841.7332102 2018-09-05 00:00:00+00:00 None 1 [6.48583858e+08]
WY YDD HHZ 01 648583841.7332102 2018-09-05 00:00:00+00:00 None 1 [6.48583858e+08]
WY YEE HHE 01 296336585.12829214 2016-09-07 00:00:00+00:00 2018-08-30 23:59:59+00:00 1 [2.96336573e+08]
WY YEE HHE 01 301719940.887643 2021-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YEE HHN 01 296336585.12829214 2016-09-07 00:00:00+00:00 2018-08-30 23:59:59+00:00 1 [2.96336573e+08]
WY YEE HHN 01 301719940.887643 2021-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YEE HHZ 01 296336585.12829214 2016-09-07 00:00:00+00:00 2018-08-30 23:59:59+00:00 1 [2.96336573e+08]
WY YEE HHZ 01 301719940.887643 2021-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YFT HHE 01 296336585.12829214 2013-09-23 00:00:00+00:00 2016-06-18 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHE 01 296336585.12829214 2016-06-19 00:00:00+00:00 2020-09-14 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHE 01 301719940.887643 2020-09-15 00:00:00+00:00 2022-09-08 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHE 01 301719940.887643 2022-09-09 00:00:00+00:00 2023-08-09 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHE 01 301719940.887643 2023-08-10 00:00:00+00:00 None 1 [2.96336573e+08]
WY YFT HHE    535285533.50222194 2010-08-19 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YFT HHN 01 296336585.12829214 2013-09-23 00:00:00+00:00 2016-06-18 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHN 01 296336585.12829214 2016-06-19 00:00:00+00:00 2020-09-14 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHN 01 301719940.887643 2020-09-15 00:00:00+00:00 2022-09-08 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHN 01 301719940.887643 2022-09-09 00:00:00+00:00 2023-08-09 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHN 01 301719940.887643 2023-08-10 00:00:00+00:00 None 1 [2.96336573e+08]
WY YFT HHN    535285533.50222194 2010-08-19 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YFT HHZ 01 296336585.12829214 2013-09-23 00:00:00+00:00 2016-06-18 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHZ 01 296336585.12829214 2016-06-19 00:00:00+00:00 2020-09-14 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHZ 01 301719940.887643 2020-09-15 00:00:00+00:00 2022-09-08 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHZ 01 301719940.887643 2022-09-09 00:00:00+00:00 2023-08-09 23:59:59+00:00 1 [2.96336573e+08]
WY YFT HHZ 01 301719940.887643 2023-08-10 00:00:00+00:00 None 1 [2.96336573e+08]
WY YFT HHZ    535285533.50222194 2010-08-19 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHB HHE 01 301719940.887643 2020-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YHB HHE    466228910.3786698 2011-09-03 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]
WY YHB HHN 01 301719940.887643 2020-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YHB HHN    466228910.3786698 2011-09-03 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]
WY YHB HHZ 01 301719940.887643 2020-09-11 00:00:00+00:00 None 1 [3.0172e+08]
WY YHB HHZ    466228910.3786698 2011-09-03 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]
WY YHH HHE 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-26 23:59:59+00:00 1 [5.35285524e+08]
WY YHH HHE    535285533.50222194 2010-08-21 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHH HHN 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-26 23:59:59+00:00 1 [5.35285524e+08]
WY YHH HHN    535285533.50222194 2010-08-21 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHH HHZ 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-26 23:59:59+00:00 1 [5.35285524e+08]
WY YHH HHZ    535285533.50222194 2010-08-21 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHL HHE 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YHL HHE    535285533.50222194 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHL HHN 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YHL HHN    535285533.50222194 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHL HHZ 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YHL HHZ    535285533.50222194 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YHR HHE 01 535285533.50222194 2014-08-28 00:00:00+00:00 None 1 [5.35285524e+08]
WY YHR HHN 01 535285533.50222194 2014-08-28 00:00:00+00:00 None 1 [5.35285524e+08]
WY YHR HHZ 01 535285533.50222194 2014-08-28 00:00:00+00:00 None 1 [5.35285524e+08]
WY YJC EHE 01 423432202.8791264 2013-04-01 00:00:00+00:00 2023-08-08 14:00:00+00:00 1 [4.23578004e+08]
WY YJC EHE    423578000.1818162 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.23578004e+08]
WY YJC EHN 01 431399857.4911888 2013-04-01 00:00:00+00:00 2023-08-08 14:00:00+00:00 1 [4.31548653e+08]
WY YJC EHN    431548656.6315656 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.31548653e+08]
WY YJC EHZ 01 432187358.2377299 2013-04-01 00:00:00+00:00 2023-08-08 14:00:00+00:00 1 [4.32338087e+08]
WY YJC EHZ    432338082.66971976 2011-09-02 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.32338087e+08]
WY YJC HHE 01 301719940.887643 2023-08-08 14:00:00+00:00 None 1 [3.0172e+08]
WY YJC HHN 01 301719940.887643 2023-08-08 14:00:00+00:00 None 1 [3.0172e+08]
WY YJC HHZ 01 301719940.887643 2023-08-08 14:00:00+00:00 None 1 [3.0172e+08]
WY YMC EHE 01 2120126419.535785 2013-08-28 00:00:00+00:00 None 1 [2.12012647e+09]
WY YMC EHN 01 2091214360.4228492 2013-08-28 00:00:00+00:00 None 1 [2.0912144e+09]
WY YMC EHZ 01 129221593.54404365 2013-04-01 00:00:00+00:00 2013-08-27 23:59:59+00:00 1 [1.29221597e+08]
WY YMC EHZ 01 2080344088.280311 2013-08-28 00:00:00+00:00 2014-08-28 23:59:59+00:00 1 [2.08034413e+09]
WY YMC EHZ 01 1568648706.7278702 2014-08-29 00:00:00+00:00 None 1 [1.56864864e+09]
WY YML EHE 01 257787469.35415965 2013-04-01 00:00:00+00:00 None 1 [2.57787465e+08]
WY YML EHE    257787469.35415965 2010-05-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [2.57787465e+08]
WY YML EHN 01 252671916.1007854 2013-04-01 00:00:00+00:00 None 1 [2.52671924e+08]
WY YML EHN    252671916.1007854 2010-05-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [2.52671924e+08]
WY YML EHZ 01 259658493.06291044 2013-04-01 00:00:00+00:00 None 1 [2.59658494e+08]
WY YML EHZ    259658493.06291044 2010-05-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [2.59658494e+08]
WY YMP HHE 01 535285533.50222194 2015-09-10 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMP HHN 01 535285533.50222194 2015-09-10 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMP HHZ 01 535285533.50222194 2015-09-10 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMR HHE 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMR HHE    535285533.50222194 2010-08-18 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YMR HHN 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMR HHN    535285533.50222194 2010-08-18 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YMR HHZ 01 535285533.50222194 2013-04-01 00:00:00+00:00 None 1 [5.35285524e+08]
WY YMR HHZ    535285533.50222194 2010-08-18 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YMV HHE 01 300039260.10393167 2023-08-10 00:00:00+00:00 None 1 [3.0172e+08]
WY YMV HHN 01 300039260.10393167 2023-08-10 00:00:00+00:00 None 1 [3.0172e+08]
WY YMV HHZ 01 300039260.10393167 2023-08-10 00:00:00+00:00 None 1 [3.0172e+08]
WY YNE HHE 01 471251844.9084544 2013-08-22 00:00:00+00:00 2018-08-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNE HHE 01 301719940.887643 2018-09-01 00:00:00+00:00 None 1 [2.96336573e+08]
WY YNE HHE    471251844.9084544 2012-09-25 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNE HHN 01 471251844.9084544 2013-08-22 00:00:00+00:00 2018-08-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNE HHN 01 301719940.887643 2018-09-01 00:00:00+00:00 None 1 [2.96336573e+08]
WY YNE HHN    471251844.9084544 2012-09-25 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNE HHZ 01 471251844.9084544 2013-08-22 00:00:00+00:00 2018-08-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNE HHZ 01 301719940.887643 2018-09-01 00:00:00+00:00 None 1 [2.96336573e+08]
WY YNE HHZ    471251844.9084544 2012-09-25 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.71251829e+08]
WY YNM HHE 01 499277563.71941465 2013-04-01 00:00:00+00:00 2023-08-08 23:59:59+00:00 1 [5.25009654e+08]
WY YNM HHN 01 499277563.71941465 2013-04-01 00:00:00+00:00 2023-08-08 23:59:59+00:00 1 [5.25009654e+08]
WY YNM HHZ 01 499277563.71941465 2013-04-01 00:00:00+00:00 2023-08-08 23:59:59+00:00 1 [5.25009654e+08]
WY YNR HHE 01 803149525.5057838 2013-04-01 00:00:00+00:00 2015-08-25 23:59:59+00:00 1 [8.03149524e+08]
WY YNR HHE 01 535285533.50222194 2015-08-26 00:00:00+00:00 None 1 [5.35285524e+08]
WY YNR HHE    803149525.5057838 2011-09-11 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [8.03149524e+08]
WY YNR HHN 01 803149525.5057838 2013-04-01 00:00:00+00:00 2015-08-25 23:59:59+00:00 1 [8.03149524e+08]
WY YNR HHN 01 535285533.50222194 2015-08-26 00:00:00+00:00 None 1 [5.35285524e+08]
WY YNR HHN    803149525.5057838 2011-09-11 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [8.03149524e+08]
WY YNR HHZ 01 803149525.5057838 2013-04-01 00:00:00+00:00 2015-08-25 23:59:59+00:00 1 [8.03149524e+08]
WY YNR HHZ 01 535285533.50222194 2015-08-26 00:00:00+00:00 None 1 [5.35285524e+08]
WY YNR HHZ    803149525.5057838 2011-09-11 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [8.03149524e+08]
WY YPK EHE 01 792087167.8633661 2013-08-25 00:00:00+00:00 None 1 [7.92087147e+08]
WY YPK EHN 01 766045658.1128067 2013-08-25 00:00:00+00:00 None 1 [7.66045631e+08]
WY YPK EHZ 01 786296982.5270665 2013-08-25 00:00:00+00:00 None 1 [7.86296986e+08]
WY YPP HHE 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-27 23:59:59+00:00 1 [5.35285524e+08]
WY YPP HHE    535285533.50222194 2010-08-27 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YPP HHN 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-27 23:59:59+00:00 1 [5.35285524e+08]
WY YPP HHN    535285533.50222194 2010-08-27 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YPP HHZ 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-27 23:59:59+00:00 1 [5.35285524e+08]
WY YPP HHZ    535285533.50222194 2010-08-27 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHE 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-22 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHE    535285533.50222194 2011-08-30 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHN 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-22 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHN    535285533.50222194 2011-08-30 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHZ 01 504316548.6068533 2013-04-01 00:00:00+00:00 2024-09-22 23:59:59+00:00 1 [5.35285524e+08]
WY YTP HHZ    535285533.50222194 2011-08-30 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [5.35285524e+08]
WY YUF HHE 01 466228910.3786698 2013-04-01 00:00:00+00:00 2016-06-08 23:59:59+00:00 1 [4.66228912e+08]
WY YUF HHE 01 503764189.86131865 2016-06-09 00:00:00+00:00 2021-09-09 23:59:59+00:00 1 [4.80990924e+08]
WY YUF HHE 01 480999626.25602096 2021-09-10 00:00:00+00:00 None 1 [4.81e+08]
WY YUF HHE    466228910.3786698 2011-09-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]
WY YUF HHN 01 466228910.3786698 2013-04-01 00:00:00+00:00 2016-06-08 23:59:59+00:00 1 [4.66228912e+08]
WY YUF HHN 01 503764189.86131865 2016-06-09 00:00:00+00:00 2021-09-09 23:59:59+00:00 1 [4.82798977e+08]
WY YUF HHN 01 480999626.25602096 2021-09-10 00:00:00+00:00 None 1 [4.81e+08]
WY YUF HHN    466228910.3786698 2011-09-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]
WY YUF HHZ 01 466228910.3786698 2013-04-01 00:00:00+00:00 2016-06-08 23:59:59+00:00 1 [4.66228912e+08]
WY YUF HHZ 01 503764189.86131865 2016-06-09 00:00:00+00:00 2021-09-09 23:59:59+00:00 1 [4.36547979e+08]
WY YUF HHZ 01 480999626.25602096 2021-09-10 00:00:00+00:00 None 1 [4.81e+08]
WY YUF HHZ    466228910.3786698 2011-09-01 00:00:00+00:00 2013-03-31 23:59:59+00:00 1 [4.66228912e+08]

In [12]:
db_gains_df["featmag_gain"] = matching_gains
db_gains_df["featmag_gain_units"] = matching_gains_units

In [13]:
for i, row in db_gains_df[~np.isnan(db_gains_df["featmag_gain"])].iterrows():
    gain_perc_err = (abs(row["gain_vel"] - row["featmag_gain"])/row["featmag_gain"])*100
    simple_gain_perc_err = (abs(row["simple_gain_vel"] - row["featmag_gain"])/row["featmag_gain"])*100
    print(f'{row["network"]}.{row["station"]}.{row["seed_code"]}.{row["location"]:5s}{ row["channel_ondate"]}-{row["channel_offdate"]} {gain_perc_err:.4f}% {simple_gain_perc_err:.4f}%')

IW.FLWY.BH1.00   2016-10-22 04:00:00-2020-01-30 20:00:00 0.0001% 0.0000%
IW.FLWY.BH1.00   2020-01-30 20:00:00-2021-08-29 18:00:00 0.0001% 0.0000%
IW.FLWY.BH1.00   2021-08-29 18:00:00-nan 2.5852% 2.5852%
IW.FLWY.BH2.00   2016-10-22 04:00:00-2020-01-30 20:00:00 0.0001% 0.0000%
IW.FLWY.BH2.00   2020-01-30 20:00:00-2021-08-29 18:00:00 0.0001% 0.0000%
IW.FLWY.BH2.00   2021-08-29 18:00:00-nan 2.5852% 2.5852%
IW.FLWY.BHE.     2007-03-16 16:46:00-2013-07-25 14:46:00 8.9506% 8.9509%
IW.FLWY.BHN.     2007-03-16 16:46:00-2013-07-25 14:46:00 8.9506% 8.9509%
IW.FLWY.BHZ.00   2013-07-25 14:46:00-2016-10-22 04:00:00 8.9506% 8.9509%
IW.FLWY.BHZ.00   2016-10-22 04:00:00-2020-01-30 20:00:00 0.0001% 0.0000%
IW.FLWY.BHZ.00   2020-01-30 20:00:00-2021-08-29 18:00:00 0.0001% 0.0000%
IW.FLWY.BHZ.00   2021-08-29 18:00:00-nan 2.5852% 2.5852%
IW.FLWY.BHZ.     2007-03-16 16:46:00-2013-07-25 14:46:00 8.9506% 8.9509%
IW.IMW.BH1.00   2013-07-25 15:11:00-2023-09-15 17:00:00 8.9506% 8.9509%
IW.IMW.BH2.00   2013-07-25 15:11:00-2023-09-15 17:00:00 8.9506% 8.9509%
IW.IMW.BHE.     2006-08-03 20:00:00-2013-07-25 15:11:00 8.9506% 8.9509%
IW.IMW.BHN.     2006-08-03 20:00:00-2013-07-25 15:11:00 8.9506% 8.9509%
IW.IMW.BHZ.00   2013-07-25 15:11:00-2023-09-15 17:00:00 8.9506% 8.9509%
IW.IMW.BHZ.     2006-08-03 20:00:00-2013-07-25 15:11:00 8.9506% 8.9509%
PB.B206.EH1.     2008-06-28 00:00:00-nan 1.3079% 0.0000%
PB.B206.EH2.     2008-06-28 00:00:00-nan 1.3079% 0.0000%
PB.B206.EHZ.     2008-06-28 00:00:00-nan 1.3079% 0.0000%
PB.B207.EH1.     2007-10-20 00:00:00-nan 1.3079% 0.0000%
PB.B207.EH2.     2007-10-20 00:00:00-nan 1.3079% 0.0000%
PB.B207.EHZ.     2007-10-20 00:00:00-nan 1.3079% 0.0000%
PB.B208.EH1.     2007-11-01 00:00:00-nan 1.3079% 0.0000%
PB.B208.EH2.     2007-11-01 00:00:00-nan 1.3079% 0.0000%
PB.B208.EHZ.     2007-11-01 00:00:00-nan 1.3079% 0.0000%
PB.B944.EH1.     2008-08-07 00:00:00-nan 1.3079% 0.0000%
PB.B944.EH2.     2008-08-07 00:00:00-nan 1.3079% 0.0000%
PB.B944.EHZ.     2008-08-07 00:00:00-nan 1.3079% 0.0000%
PB.B945.EH1.     2008-09-04 00:00:00-nan 1.3079% 0.0000%
PB.B945.EH2.     2008-09-04 00:00:00-nan 1.3079% 0.0000%
PB.B945.EHZ.     2008-09-04 00:00:00-nan 1.3079% 0.0000%
PB.B950.EH1.     2013-10-02 00:00:00-nan 1.3079% 0.0000%
PB.B950.EH2.     2013-10-02 00:00:00-nan 1.3079% 0.0000%
PB.B950.EHZ.     2013-10-02 00:00:00-nan 1.3079% 0.0000%
TA.H17A.BHE.     2011-08-22 17:00:00-2016-10-13 18:00:00 0.0352% 0.0000%
TA.H17A.BHN.     2011-08-22 17:00:00-2016-10-13 18:00:00 0.0352% 0.0000%
TA.H17A.BHZ.     2011-08-22 17:00:00-2016-10-13 18:00:00 0.0352% 0.0000%
TA.H17A.HHE.     2015-10-16 18:00:00-2016-10-13 18:00:00 0.0204% 0.0000%
TA.H17A.HHE.     2016-10-13 18:00:00-2018-09-04 18:00:00 0.0204% 0.0000%
TA.H17A.HHN.     2015-10-16 18:00:00-2016-10-13 18:00:00 0.0204% 0.0000%
TA.H17A.HHN.     2016-10-13 18:00:00-2018-09-04 18:00:00 0.0204% 0.0000%
TA.H17A.HHZ.     2015-10-16 18:00:00-2016-10-13 18:00:00 0.0204% 0.0000%
TA.H17A.HHZ.     2016-10-13 18:00:00-2018-09-04 18:00:00 0.0204% 0.0000%
US.LKWY.BH1.00   2015-08-23 17:00:00-2018-09-27 18:00:00 0.6762% 0.6764%
US.LKWY.BH1.00   2018-09-27 18:00:00-2019-10-26 19:02:00 0.6762% 0.6764%
US.LKWY.BH1.00   2019-10-26 19:02:00-2021-08-12 00:00:00 0.6762% 0.6764%
US.LKWY.BH1.00   2021-08-12 00:00:00-2024-07-16 19:00:00 0.6762% 0.6764%
US.LKWY.BH2.00   2015-08-23 17:00:00-2018-09-27 18:00:00 0.6762% 0.6764%
US.LKWY.BH2.00   2018-09-27 18:00:00-2019-10-26 19:02:00 0.6762% 0.6764%
US.LKWY.BH2.00   2019-10-26 19:02:00-2021-08-12 00:00:00 0.6762% 0.6764%
US.LKWY.BH2.00   2021-08-12 00:00:00-2024-07-16 19:00:00 0.6762% 0.6764%
US.LKWY.BHZ.00   2011-08-09 18:00:00-2015-08-23 17:00:00 0.6762% 0.6764%
US.LKWY.BHZ.00   2015-08-23 17:00:00-2018-09-27 18:00:00 0.6762% 0.6764%
US.LKWY.BHZ.00   2018-09-27 18:00:00-2019-10-26 19:02:00 0.6762% 0.6764%
US.LKWY.BHZ.00   2019-10-26 19:02:00-2021-08-12 00:00:00 0.6762% 0.6764%
US.LKWY.BHZ.00   2021-08-12 00:00:00-2024-07-16 19:00:00 0.6762% 0.6764%
WY.YDD.HHE.01   2018-09-05 00:00:00-nan 0.0000% 0.0007%
WY.YDD.HHN.01   2018-09-05 00:00:00-nan 0.0000% 0.0007%
WY.YDD.HHZ.01   2018-09-05 00:00:00-nan 0.0000% 0.0007%
WY.YEE.HHE.01   2016-09-07 00:00:00-2018-08-30 23:59:59 0.0000% 0.0001%
WY.YEE.HHE.01   2021-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YEE.HHN.01   2016-09-07 00:00:00-2018-08-30 23:59:59 0.0000% 0.0001%
WY.YEE.HHN.01   2021-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YEE.HHZ.01   2016-09-07 00:00:00-2018-08-30 23:59:59 0.0000% 0.0001%
WY.YEE.HHZ.01   2021-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YFT.HHE.01   2013-09-23 00:00:00-2016-06-18 23:59:59 0.0000% 0.0001%
WY.YFT.HHE.01   2016-06-19 00:00:00-2020-09-14 23:59:59 0.0000% 0.0001%
WY.YFT.HHE.01   2020-09-15 00:00:00-2022-09-08 23:59:59 1.8166% 1.8167%
WY.YFT.HHE.01   2022-09-09 00:00:00-2023-08-09 23:59:59 1.8166% 1.8167%
WY.YFT.HHE.01   2023-08-10 00:00:00-nan 1.8166% 1.8167%
WY.YFT.HHE.     2010-08-19 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YFT.HHN.01   2013-09-23 00:00:00-2016-06-18 23:59:59 0.0000% 0.0001%
WY.YFT.HHN.01   2016-06-19 00:00:00-2020-09-14 23:59:59 0.0000% 0.0001%
WY.YFT.HHN.01   2020-09-15 00:00:00-2022-09-08 23:59:59 1.8166% 1.8167%
WY.YFT.HHN.01   2022-09-09 00:00:00-2023-08-09 23:59:59 1.8166% 1.8167%
WY.YFT.HHN.01   2023-08-10 00:00:00-nan 1.8166% 1.8167%
WY.YFT.HHN.     2010-08-19 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YFT.HHZ.01   2013-09-23 00:00:00-2016-06-18 23:59:59 0.0000% 0.0001%
WY.YFT.HHZ.01   2016-06-19 00:00:00-2020-09-14 23:59:59 0.0000% 0.0001%
WY.YFT.HHZ.01   2020-09-15 00:00:00-2022-09-08 23:59:59 1.8166% 1.8167%
WY.YFT.HHZ.01   2022-09-09 00:00:00-2023-08-09 23:59:59 1.8166% 1.8167%
WY.YFT.HHZ.01   2023-08-10 00:00:00-nan 1.8166% 1.8167%
WY.YFT.HHZ.     2010-08-19 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHB.HHE.01   2020-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YHB.HHE.     2011-09-03 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHB.HHN.01   2020-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YHB.HHN.     2011-09-03 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHB.HHZ.01   2020-09-11 00:00:00-nan 0.0000% 0.0000%
WY.YHB.HHZ.     2011-09-03 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHH.HHE.01   2013-04-01 00:00:00-2024-09-26 23:59:59 5.7855% 5.8941%
WY.YHH.HHE.     2010-08-21 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHH.HHN.01   2013-04-01 00:00:00-2024-09-26 23:59:59 5.7855% 5.8941%
WY.YHH.HHN.     2010-08-21 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHH.HHZ.01   2013-04-01 00:00:00-2024-09-26 23:59:59 5.7855% 5.8941%
WY.YHH.HHZ.     2010-08-21 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHL.HHE.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YHL.HHE.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHL.HHN.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YHL.HHN.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHL.HHZ.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YHL.HHZ.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YHR.HHE.01   2014-08-28 00:00:00-nan 0.0000% 0.0001%
WY.YHR.HHN.01   2014-08-28 00:00:00-nan 0.0000% 0.0001%
WY.YHR.HHZ.01   2014-08-28 00:00:00-nan 0.0000% 0.0001%
WY.YJC.EHE.01   2013-04-01 00:00:00-2023-08-08 14:00:00 0.0344% 0.0446%
WY.YJC.EHE.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0022%
WY.YJC.EHN.01   2013-04-01 00:00:00-2023-08-08 14:00:00 0.0345% 0.0446%
WY.YJC.EHN.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0022%
WY.YJC.EHZ.01   2013-04-01 00:00:00-2023-08-08 14:00:00 0.0349% 0.0442%
WY.YJC.EHZ.     2011-09-02 00:00:00-2013-03-31 23:59:59 0.0000% 0.0022%
WY.YJC.HHE.01   2023-08-08 14:00:00-nan 0.0000% 0.0000%
WY.YJC.HHN.01   2023-08-08 14:00:00-nan 0.0000% 0.0000%
WY.YJC.HHZ.01   2023-08-08 14:00:00-nan 0.0000% 0.0000%
WY.YMC.EHE.01   2013-08-28 00:00:00-nan 0.0000% 0.0001%
WY.YMC.EHN.01   2013-08-28 00:00:00-nan 0.0000% 0.0001%
WY.YMC.EHZ.01   2013-04-01 00:00:00-2013-08-27 23:59:59 0.0000% 0.0001%
WY.YMC.EHZ.01   2013-08-28 00:00:00-2014-08-28 23:59:59 0.0000% 0.0001%
WY.YMC.EHZ.01   2014-08-29 00:00:00-nan 0.0000% 0.0001%
WY.YML.EHE.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YML.EHE.     2010-05-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YML.EHN.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YML.EHN.     2010-05-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YML.EHZ.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YML.EHZ.     2010-05-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YMP.HHE.01   2015-09-10 00:00:00-nan 0.0000% 0.0001%
WY.YMP.HHN.01   2015-09-10 00:00:00-nan 0.0000% 0.0001%
WY.YMP.HHZ.01   2015-09-10 00:00:00-nan 0.0000% 0.0001%
WY.YMR.HHE.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YMR.HHE.     2010-08-18 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YMR.HHN.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YMR.HHN.     2010-08-18 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YMR.HHZ.01   2013-04-01 00:00:00-nan 0.0000% 0.0001%
WY.YMR.HHZ.     2010-08-18 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YMV.HHE.01   2023-08-10 00:00:00-nan 0.5571% 0.0000%
WY.YMV.HHN.01   2023-08-10 00:00:00-nan 0.5571% 0.0000%
WY.YMV.HHZ.01   2023-08-10 00:00:00-nan 0.5571% 0.0000%
WY.YNE.HHE.01   2013-08-22 00:00:00-2018-08-31 23:59:59 0.0000% 0.0001%
WY.YNE.HHE.01   2018-09-01 00:00:00-nan 1.8166% 1.8167%
WY.YNE.HHE.     2012-09-25 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YNE.HHN.01   2013-08-22 00:00:00-2018-08-31 23:59:59 0.0000% 0.0001%
WY.YNE.HHN.01   2018-09-01 00:00:00-nan 1.8166% 1.8167%
WY.YNE.HHN.     2012-09-25 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YNE.HHZ.01   2013-08-22 00:00:00-2018-08-31 23:59:59 0.0000% 0.0001%
WY.YNE.HHZ.01   2018-09-01 00:00:00-nan 1.8166% 1.8167%
WY.YNE.HHZ.     2012-09-25 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YNM.HHE.01   2013-04-01 00:00:00-2023-08-08 23:59:59 4.9013% 5.0109%
WY.YNM.HHN.01   2013-04-01 00:00:00-2023-08-08 23:59:59 4.9013% 5.0109%
WY.YNM.HHZ.01   2013-04-01 00:00:00-2023-08-08 23:59:59 4.9013% 5.0109%
WY.YNR.HHE.01   2013-04-01 00:00:00-2015-08-25 23:59:59 0.0000% 0.0001%
WY.YNR.HHE.01   2015-08-26 00:00:00-nan 0.0000% 0.0001%
WY.YNR.HHE.     2011-09-11 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YNR.HHN.01   2013-04-01 00:00:00-2015-08-25 23:59:59 0.0000% 0.0001%
WY.YNR.HHN.01   2015-08-26 00:00:00-nan 0.0000% 0.0001%
WY.YNR.HHN.     2011-09-11 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YNR.HHZ.01   2013-04-01 00:00:00-2015-08-25 23:59:59 0.0000% 0.0001%
WY.YNR.HHZ.01   2015-08-26 00:00:00-nan 0.0000% 0.0001%
WY.YNR.HHZ.     2011-09-11 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YPK.EHE.01   2013-08-25 00:00:00-nan 0.0000% 0.0022%
WY.YPK.EHN.01   2013-08-25 00:00:00-nan 0.0000% 0.0022%
WY.YPK.EHZ.01   2013-08-25 00:00:00-nan 0.0000% 0.0022%
WY.YPP.HHE.01   2013-04-01 00:00:00-2024-09-27 23:59:59 5.7855% 5.8941%
WY.YPP.HHE.     2010-08-27 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YPP.HHN.01   2013-04-01 00:00:00-2024-09-27 23:59:59 5.7855% 5.8941%
WY.YPP.HHN.     2010-08-27 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YPP.HHZ.01   2013-04-01 00:00:00-2024-09-27 23:59:59 5.7855% 5.8941%
WY.YPP.HHZ.     2010-08-27 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YTP.HHE.01   2013-04-01 00:00:00-2024-09-22 23:59:59 5.7855% 5.8941%
WY.YTP.HHE.     2011-08-30 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YTP.HHN.01   2013-04-01 00:00:00-2024-09-22 23:59:59 5.7855% 5.8941%
WY.YTP.HHN.     2011-08-30 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YTP.HHZ.01   2013-04-01 00:00:00-2024-09-22 23:59:59 5.7855% 5.8941%
WY.YTP.HHZ.     2011-08-30 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YUF.HHE.01   2013-04-01 00:00:00-2016-06-08 23:59:59 0.0000% 0.0001%
WY.YUF.HHE.01   2016-06-09 00:00:00-2021-09-09 23:59:59 4.7347% 4.6388%
WY.YUF.HHE.01   2021-09-10 00:00:00-nan 0.0001% 0.0000%
WY.YUF.HHE.     2011-09-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YUF.HHN.01   2013-04-01 00:00:00-2016-06-08 23:59:59 0.0000% 0.0001%
WY.YUF.HHN.01   2016-06-09 00:00:00-2021-09-09 23:59:59 4.3424% 4.2469%
WY.YUF.HHN.01   2021-09-10 00:00:00-nan 0.0001% 0.0000%
WY.YUF.HHN.     2011-09-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%
WY.YUF.HHZ.01   2013-04-01 00:00:00-2016-06-08 23:59:59 0.0000% 0.0001%
WY.YUF.HHZ.01   2016-06-09 00:00:00-2021-09-09 23:59:59 15.3972% 15.2916%
WY.YUF.HHZ.01   2021-09-10 00:00:00-nan 0.0001% 0.0000%
WY.YUF.HHZ.     2011-09-01 00:00:00-2013-03-31 23:59:59 0.0000% 0.0001%

In [14]:
net = "IW"
stat = "FLWY"
loc = "00"
chan = "BH2"
gains_df[(gains_df["network"] == net) & 
            (gains_df["station"] == stat) & 
            #(gains_df["location"] == loc) & 
            (gains_df["channel"] == chan)].sort_values("mindate")

,network,station,location,channel,gain,gain_units,channel_dip,channel_azimuth,mindate,maxdate
12322,IW,FLWY,00,BH2,462429000.0,DU/M/S,0.0,90.0,2016-11-17 06:08:44.755000+00:00,2021-07-31 08:11:14.434572+00:00
47608,IW,FLWY,00,BH2,301720000.0,DU/M/S,0.0,92.8,2021-09-08 17:01:40.424286+00:00,2023-12-17 03:22:16.120020+00:00

In [15]:
db_gains_df[(db_gains_df["network"] == net) & 
            (db_gains_df["station"] == stat) & 
            # (db_gains_df["location"] == loc) & 
            (db_gains_df["seed_code"] == chan)].sort_values("channel_ondate")

,channel_id,network,station,location,seed_code,channel_samp_rate,sensit_units,sensit_freq,sensit_val,gain_vel,receiver_lat,receiver_lon,channel_azimuth,channel_ondate,channel_offdate,simple_gain_vel,featmag_gain,featmag_gain_units
7,959,IW,FLWY,00,BH2,40.0,m/s,0.05,1.145990e+09,1.145993e+09,44.083002,-110.699888,90.0,2013-07-25 14:46:00,2016-10-22 04:00:00,1.145990e+09,NaN,None
8,569,IW,FLWY,00,BH2,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,90.0,2016-10-22 04:00:00,2020-01-30 20:00:00,4.624290e+08,462429000.0,DU/M/S
9,378,IW,FLWY,00,BH2,40.0,m/s,0.02,4.624290e+08,4.624283e+08,44.083002,-110.699888,90.0,2020-01-30 20:00:00,2021-08-29 18:00:00,4.624290e+08,462429000.0,DU/M/S
10,5,IW,FLWY,00,BH2,40.0,m/s,0.02,2.939200e+08,2.939199e+08,44.083002,-110.699888,92.8,2021-08-29 18:00:00,NaN,2.939200e+08,301720000.0,DU/M/S

In [16]:
db_gains_df["sensit_units"].value_counts()

sensit_units
m         227
m/s       164
M/S        48
V          30
m/s**2      3
Name: count, dtype: int64

In [17]:
db_gains_df.to_csv("../files/db_featmag_gains_S.csv", index=False)